// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYPQ2FupbGy2VOxZxs0ZgicvVnf2OUaT8',
    appId: '1:522071991490:web:e64279793b09099e4e875b',
    messagingSenderId: '522071991490',
    projectId: 'vipromi-3c29d',
    authDomain: 'vipromi-3c29d.firebaseapp.com',
    storageBucket: 'vipromi-3c29d.firebasestorage.app',
    measurementId: 'G-PM6FHY3Y06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiiVQYDU-XpzervcI90xSNtr7SmlX4hgY',
    appId: '1:522071991490:android:b10406b634b673394e875b',
    messagingSenderId: '522071991490',
    projectId: 'vipromi-3c29d',
    storageBucket: 'vipromi-3c29d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVZEaKiGF16C4ehzGtvCqUsEx-LDZOcd0',
    appId: '1:522071991490:ios:073c54f6d106a45a4e875b',
    messagingSenderId: '522071991490',
    projectId: 'vipromi-3c29d',
    storageBucket: 'vipromi-3c29d.firebasestorage.app',
    iosBundleId: 'com.example.vipromi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVZEaKiGF16C4ehzGtvCqUsEx-LDZOcd0',
    appId: '1:522071991490:ios:073c54f6d106a45a4e875b',
    messagingSenderId: '522071991490',
    projectId: 'vipromi-3c29d',
    storageBucket: 'vipromi-3c29d.firebasestorage.app',
    iosBundleId: 'com.example.vipromi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYPQ2FupbGy2VOxZxs0ZgicvVnf2OUaT8',
    appId: '1:522071991490:web:93c4384edbea29e24e875b',
    messagingSenderId: '522071991490',
    projectId: 'vipromi-3c29d',
    authDomain: 'vipromi-3c29d.firebaseapp.com',
    storageBucket: 'vipromi-3c29d.firebasestorage.app',
    measurementId: 'G-Z74HNJ0D5B',
  );
}
